### ISSUE TITLE
add geo-coordinates?

### ISSUE THREAD

**Issue by steltenpower** [poef/jsontag#4]
With or without a height? compared to what? There must be a OGC standard

**Comment by poef** [comment]
This is on my radar. I'm contemplating using the PostgreSQL geo types. But I think there is an opportunity to use more general purpose points/shapes, so that you could also describe vector graphics. Not sure yet.

**Comment by poef** [comment]
I think I'll leave the geometric types out of jsontag for now. You can always simulate them with extra class or other attributes. The `<range>` type allows for lines in 2d space, the other geo types can be emulated with `<object>` and `<array>` tags.
